#server:
#  port: 8080
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates: 
#            - Path=/api/auth/**
#        - id: post-service
#          uri: lb://post-service
#          predicates: 
#            - Path=/api/post/**
#          filters:
#          - AuthenticationFilter
    